version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: active-bistro
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: